#!/bin/bash
#Debug: echo "variable 1 is $1"

# Gabe's HDR Checker Tool
# October 12, 2022

# Add Font Formatting Tags
bold=$(tput bold)
normal=$(tput sgr0)

# Intialization
echo "${bold}Gabe's HDR Checker${normal} v1.01r18"
echo "-----------------------------------------------------------"

# Start Processing the requested file.
echo "Begin video processing..."
output=`ffprobe -v quiet -show_streams -select_streams v:0 $1 | grep ^color_transfer=`

echo "Checking video file: Analyzing Colour Profile..."
output=`ffprobe -v quiet -show_streams -select_streams v:0 $1 | grep ^color_transfer=`
echo "Done!"

echo "Checking video file: Analyzing Colour Primaries..."
output=`ffprobe -v quiet -show_streams -select_streams v:0 $1 | grep ^color_transfer=`
echo "Done!"

echo "Checking video file: Analyzing Matrix & Video Codec..."
output=`ffprobe -v quiet -show_streams -select_streams v:0 $1 | grep ^color_transfer=`
echo "Done!"

# Process output of command into HDR Formats
if [[ $output == "color_transfer=arib-std-b67" ]]
then
echo "-----------------------------------------------------------"
echo "Target video $1 is ${bold}HDR${normal} and encoded in ${bold}[HLG / Dolby Vision] ${normal}"
echo "-----------------------------------------------------------"

elif [[ $output == "color_transfer=smpte2084" ]]
then
echo "-----------------------------------------------------------"
echo "Target video $1 is ${bold}HDR${normal} and encoded in ${bold}[PQ]${normal}"
echo "-----------------------------------------------------------"

else
echo "Target video $1 is SDR or invalid file name. Ensure the filename has no spaces or backslashes."
fi

# You've reached the end of the file.

